pdf("smartpca.pdf")
data=read.table("plot.txt")
pop=data[,1]
ind=data[,2]
PC1=data[,3]
PC2=data[,4]
# layout(matrix(c(1,2)),widths=c(2,1),heights=c(3,1))
# par(mar=c(4,4,1,5))
plot(PC1,PC2,type="n")
frame=data.frame(PC1=PC1,PC2=PC2,name=pop,region=pop)
light=c("#FFDAB9", "#ABF4DC", "#D3D3D3", "#b1c8f3", "#ffbbea", "#c8b0f5", "#e2ffa8", "#c1fffa", "#f3f3a9", "#fa9c9c")
deep=c("#CCCC00", "#3787B4", "#00CD66", "#6B8E23", "#D02090", "#FF8C69", "#905aff", "#20B2AA", "#FFC534", "#FFFF00", "#6F96F2", "#8D5223", "#FF1493")


# COLOR SETTINGS
Han_col=light[1]
Austronesian_col=light[2]
HmongMien_col=light[3]
JapaneseKorean_col=light[4]
Mongolian_col=light[5]
TaiKadai_col=light[6]
TibetanBurman_col=light[7]
Tungusic_col=light[8]
AncientYellowRiver_col=deep[1]
AncientAmurRiver_col=deep[2]
AncientNepal_col=deep[3]
AncientSouthernAsia_col=deep[4]
AncientMongolia_col=deep[5]
AncientCentralAsian_col=deep[6]
AncientRussia_col=deep[7]
Xianbei_related_col="#FF0000"
target_col = 'red'
target_bg = 'yellow'

# PLOT# Han
reg="Han_Fujian"
points(subset(frame,region==reg)$PC1,subset(frame,region==reg)$PC2,pch=1,col=Han_col,bg=Han_col,cex=0.6)
reg="Han_Guangdong"
points(subset(frame,region==reg)$PC1,subset(frame,region==reg)$PC2,pch=2,col=Han_col,bg=Han_col,cex=0.6)
reg="Han_Henan"
points(subset(frame,region==reg)$PC1,subset(frame,region==reg)$PC2,pch=3,col=Han_col,bg=Han_col,cex=0.6)
reg="Han_Hubei"
points(subset(frame,region==reg)$PC1,subset(frame,region==reg)$PC2,pch=4,col=Han_col,bg=Han_col,cex=0.6)
reg="Han_Jiangsu"
points(subset(frame,region==reg)$PC1,subset(frame,region==reg)$PC2,pch=5,col=Han_col,bg=Han_col,cex=0.6)
reg="Han_Shandong"
points(subset(frame,region==reg)$PC1,subset(frame,region==reg)$PC2,pch=6,col=Han_col,bg=Han_col,cex=0.6)
reg="Han_Shanghai"
points(subset(frame,region==reg)$PC1,subset(frame,region==reg)$PC2,pch=7,col=Han_col,bg=Han_col,cex=0.6)
reg="Han_Shanxi"
points(subset(frame,region==reg)$PC1,subset(frame,region==reg)$PC2,pch=8,col=Han_col,bg=Han_col,cex=0.6)
reg="Han_Sichuan"
points(subset(frame,region==reg)$PC1,subset(frame,region==reg)$PC2,pch=9,col=Han_col,bg=Han_col,cex=0.6)
reg="Han_Zhejiang"
points(subset(frame,region==reg)$PC1,subset(frame,region==reg)$PC2,pch=10,col=Han_col,bg=Han_col,cex=0.6)
reg="Han_Chongqing"
points(subset(frame,region==reg)$PC1,subset(frame,region==reg)$PC2,pch=11,col=Han_col,bg=Han_col,cex=0.6)
reg="Han_NChina"
points(subset(frame,region==reg)$PC1,subset(frame,region==reg)$PC2,pch=12,col=Han_col,bg=Han_col,cex=0.6)
reg="Han_HGDP"
points(subset(frame,region==reg)$PC1,subset(frame,region==reg)$PC2,pch=13,col=Han_col,bg=Han_col,cex=0.6)
# Austronesian
reg="Ami"
points(subset(frame,region==reg)$PC1,subset(frame,region==reg)$PC2,pch=1,col=Austronesian_col,bg=Austronesian_col,cex=0.6)
reg="Malay"
points(subset(frame,region==reg)$PC1,subset(frame,region==reg)$PC2,pch=2,col=Austronesian_col,bg=Austronesian_col,cex=0.6)
reg="Atayal"
points(subset(frame,region==reg)$PC1,subset(frame,region==reg)$PC2,pch=3,col=Austronesian_col,bg=Austronesian_col,cex=0.6)
reg="Tagalog"
points(subset(frame,region==reg)$PC1,subset(frame,region==reg)$PC2,pch=4,col=Austronesian_col,bg=Austronesian_col,cex=0.6)
# Hmong-Mien
reg="She"
points(subset(frame,region==reg)$PC1,subset(frame,region==reg)$PC2,pch=1,col=HmongMien_col,bg=HmongMien_col,cex=0.6)
reg="Dao"
points(subset(frame,region==reg)$PC1,subset(frame,region==reg)$PC2,pch=2,col=HmongMien_col,bg=HmongMien_col,cex=0.6)
reg="Miao"
points(subset(frame,region==reg)$PC1,subset(frame,region==reg)$PC2,pch=3,col=HmongMien_col,bg=HmongMien_col,cex=0.6)
reg="Gelao"
points(subset(frame,region==reg)$PC1,subset(frame,region==reg)$PC2,pch=4,col=HmongMien_col,bg=HmongMien_col,cex=0.6)
reg="Hmong"
points(subset(frame,region==reg)$PC1,subset(frame,region==reg)$PC2,pch=5,col=HmongMien_col,bg=HmongMien_col,cex=0.6)
# Japanese-Korean
reg="Korean"
points(subset(frame,region==reg)$PC1,subset(frame,region==reg)$PC2,pch=1,col=JapaneseKorean_col,bg=JapaneseKorean_col,cex=0.6)
reg="Japanese"
points(subset(frame,region==reg)$PC1,subset(frame,region==reg)$PC2,pch=2,col=JapaneseKorean_col,bg=JapaneseKorean_col,cex=0.6)
# Mongolian
reg="Tu"
points(subset(frame,region==reg)$PC1,subset(frame,region==reg)$PC2,pch=1,col=Mongolian_col,bg=Mongolian_col,cex=0.6)
reg="Daur"
points(subset(frame,region==reg)$PC1,subset(frame,region==reg)$PC2,pch=2,col=Mongolian_col,bg=Mongolian_col,cex=0.6)
reg="Yugur"
points(subset(frame,region==reg)$PC1,subset(frame,region==reg)$PC2,pch=3,col=Mongolian_col,bg=Mongolian_col,cex=0.6)
reg="Bonan"
points(subset(frame,region==reg)$PC1,subset(frame,region==reg)$PC2,pch=4,col=Mongolian_col,bg=Mongolian_col,cex=0.6)
reg="Buryat"
points(subset(frame,region==reg)$PC1,subset(frame,region==reg)$PC2,pch=5,col=Mongolian_col,bg=Mongolian_col,cex=0.6)
reg="Mongol"
points(subset(frame,region==reg)$PC1,subset(frame,region==reg)$PC2,pch=6,col=Mongolian_col,bg=Mongolian_col,cex=0.6)
reg="Mongola"
points(subset(frame,region==reg)$PC1,subset(frame,region==reg)$PC2,pch=7,col=Mongolian_col,bg=Mongolian_col,cex=0.6)
reg="Dongxiang"
points(subset(frame,region==reg)$PC1,subset(frame,region==reg)$PC2,pch=8,col=Mongolian_col,bg=Mongolian_col,cex=0.6)
# Tai-Kadai
reg="Dai"
points(subset(frame,region==reg)$PC1,subset(frame,region==reg)$PC2,pch=1,col=TaiKadai_col,bg=TaiKadai_col,cex=0.6)
reg="Zhuang"
points(subset(frame,region==reg)$PC1,subset(frame,region==reg)$PC2,pch=2,col=TaiKadai_col,bg=TaiKadai_col,cex=0.6)
reg="Li"
points(subset(frame,region==reg)$PC1,subset(frame,region==reg)$PC2,pch=3,col=TaiKadai_col,bg=TaiKadai_col,cex=0.6)
reg="Dong_Hunan"
points(subset(frame,region==reg)$PC1,subset(frame,region==reg)$PC2,pch=4,col=TaiKadai_col,bg=TaiKadai_col,cex=0.6)
reg="Thai"
points(subset(frame,region==reg)$PC1,subset(frame,region==reg)$PC2,pch=5,col=TaiKadai_col,bg=TaiKadai_col,cex=0.6)
reg="Tay"
points(subset(frame,region==reg)$PC1,subset(frame,region==reg)$PC2,pch=6,col=TaiKadai_col,bg=TaiKadai_col,cex=0.6)
reg="BoY"
points(subset(frame,region==reg)$PC1,subset(frame,region==reg)$PC2,pch=7,col=TaiKadai_col,bg=TaiKadai_col,cex=0.6)
reg="CoLao"
points(subset(frame,region==reg)$PC1,subset(frame,region==reg)$PC2,pch=8,col=TaiKadai_col,bg=TaiKadai_col,cex=0.6)
reg="Nung"
points(subset(frame,region==reg)$PC1,subset(frame,region==reg)$PC2,pch=9,col=TaiKadai_col,bg=TaiKadai_col,cex=0.6)
# Tibetan-Burman
reg="Yi"
points(subset(frame,region==reg)$PC1,subset(frame,region==reg)$PC2,pch=1,col=TibetanBurman_col,bg=TibetanBurman_col,cex=0.6)
reg="Naxi"
points(subset(frame,region==reg)$PC1,subset(frame,region==reg)$PC2,pch=2,col=TibetanBurman_col,bg=TibetanBurman_col,cex=0.6)
reg="Tujia"
points(subset(frame,region==reg)$PC1,subset(frame,region==reg)$PC2,pch=3,col=TibetanBurman_col,bg=TibetanBurman_col,cex=0.6)
reg="China_Lahu"
points(subset(frame,region==reg)$PC1,subset(frame,region==reg)$PC2,pch=4,col=TibetanBurman_col,bg=TibetanBurman_col,cex=0.6)
reg="Tibetan_Chamdo"
points(subset(frame,region==reg)$PC1,subset(frame,region==reg)$PC2,pch=5,col=TibetanBurman_col,bg=TibetanBurman_col,cex=0.6)
reg="Tibetan_Lhasa"
points(subset(frame,region==reg)$PC1,subset(frame,region==reg)$PC2,pch=6,col=TibetanBurman_col,bg=TibetanBurman_col,cex=0.6)
reg="Tibetan_Yunnan"
points(subset(frame,region==reg)$PC1,subset(frame,region==reg)$PC2,pch=7,col=TibetanBurman_col,bg=TibetanBurman_col,cex=0.6)
reg="Tibetan_Yajiang"
points(subset(frame,region==reg)$PC1,subset(frame,region==reg)$PC2,pch=8,col=TibetanBurman_col,bg=TibetanBurman_col,cex=0.6)
reg="Tibetan_Xinlong"
points(subset(frame,region==reg)$PC1,subset(frame,region==reg)$PC2,pch=9,col=TibetanBurman_col,bg=TibetanBurman_col,cex=0.6)
# Tungusic
reg="Xibo"
points(subset(frame,region==reg)$PC1,subset(frame,region==reg)$PC2,pch=1,col=Tungusic_col,bg=Tungusic_col,cex=0.6)
reg="Hezhen"
points(subset(frame,region==reg)$PC1,subset(frame,region==reg)$PC2,pch=2,col=Tungusic_col,bg=Tungusic_col,cex=0.6)
reg="Oroqen"
points(subset(frame,region==reg)$PC1,subset(frame,region==reg)$PC2,pch=3,col=Tungusic_col,bg=Tungusic_col,cex=0.6)
reg="Ulchi"
points(subset(frame,region==reg)$PC1,subset(frame,region==reg)$PC2,pch=4,col=Tungusic_col,bg=Tungusic_col,cex=0.6)
reg="Evenk_FarEast"
points(subset(frame,region==reg)$PC1,subset(frame,region==reg)$PC2,pch=5,col=Tungusic_col,bg=Tungusic_col,cex=0.6)
# Ancient Yellow River
reg="Yumin"
points(subset(frame,region==reg)$PC1,subset(frame,region==reg)$PC2,pch=1,col=AncientYellowRiver_col,bg=AncientYellowRiver_col,cex=0.6)
reg="Bianbian"
points(subset(frame,region==reg)$PC1,subset(frame,region==reg)$PC2,pch=2,col=AncientYellowRiver_col,bg=AncientYellowRiver_col,cex=0.6)
reg="Boshan"
points(subset(frame,region==reg)$PC1,subset(frame,region==reg)$PC2,pch=3,col=AncientYellowRiver_col,bg=AncientYellowRiver_col,cex=0.6)
reg="Xiaogao"
points(subset(frame,region==reg)$PC1,subset(frame,region==reg)$PC2,pch=4,col=AncientYellowRiver_col,bg=AncientYellowRiver_col,cex=0.6)
reg="Xiaojingshan"
points(subset(frame,region==reg)$PC1,subset(frame,region==reg)$PC2,pch=5,col=AncientYellowRiver_col,bg=AncientYellowRiver_col,cex=0.6)
reg="Miaozigou_MN"
points(subset(frame,region==reg)$PC1,subset(frame,region==reg)$PC2,pch=6,col=AncientYellowRiver_col,bg=AncientYellowRiver_col,cex=0.6)
reg="YR_MN"
points(subset(frame,region==reg)$PC1,subset(frame,region==reg)$PC2,pch=7,col=AncientYellowRiver_col,bg=AncientYellowRiver_col,cex=0.6)
reg="YR_LN"
points(subset(frame,region==reg)$PC1,subset(frame,region==reg)$PC2,pch=8,col=AncientYellowRiver_col,bg=AncientYellowRiver_col,cex=0.6)
reg="YR_LBIA"
points(subset(frame,region==reg)$PC1,subset(frame,region==reg)$PC2,pch=9,col=AncientYellowRiver_col,bg=AncientYellowRiver_col,cex=0.6)
reg="Shimao_LN"
points(subset(frame,region==reg)$PC1,subset(frame,region==reg)$PC2,pch=10,col=AncientYellowRiver_col,bg=AncientYellowRiver_col,cex=0.6)
reg="Upper_YR_LN"
points(subset(frame,region==reg)$PC1,subset(frame,region==reg)$PC2,pch=11,col=AncientYellowRiver_col,bg=AncientYellowRiver_col,cex=0.6)
reg="Upper_YR_IA"
points(subset(frame,region==reg)$PC1,subset(frame,region==reg)$PC2,pch=12,col=AncientYellowRiver_col,bg=AncientYellowRiver_col,cex=0.6)
# Ancient Amur River
reg="AR19K"
points(subset(frame,region==reg)$PC1,subset(frame,region==reg)$PC2,pch=1,col=AncientAmurRiver_col,bg=AncientAmurRiver_col,cex=0.6)
reg="AR14K"
points(subset(frame,region==reg)$PC1,subset(frame,region==reg)$PC2,pch=2,col=AncientAmurRiver_col,bg=AncientAmurRiver_col,cex=0.6)
reg="ARpost9K"
points(subset(frame,region==reg)$PC1,subset(frame,region==reg)$PC2,pch=3,col=AncientAmurRiver_col,bg=AncientAmurRiver_col,cex=0.6)
reg="AR_EN"
points(subset(frame,region==reg)$PC1,subset(frame,region==reg)$PC2,pch=4,col=AncientAmurRiver_col,bg=AncientAmurRiver_col,cex=0.6)
reg="AR_IA"
points(subset(frame,region==reg)$PC1,subset(frame,region==reg)$PC2,pch=5,col=AncientAmurRiver_col,bg=AncientAmurRiver_col,cex=0.6)
reg="HMMH_MN"
points(subset(frame,region==reg)$PC1,subset(frame,region==reg)$PC2,pch=6,col=AncientAmurRiver_col,bg=AncientAmurRiver_col,cex=0.6)
reg="WLR_MN"
points(subset(frame,region==reg)$PC1,subset(frame,region==reg)$PC2,pch=7,col=AncientAmurRiver_col,bg=AncientAmurRiver_col,cex=0.6)
reg="WLR_LN"
points(subset(frame,region==reg)$PC1,subset(frame,region==reg)$PC2,pch=8,col=AncientAmurRiver_col,bg=AncientAmurRiver_col,cex=0.6)
reg="WLR_BA"
points(subset(frame,region==reg)$PC1,subset(frame,region==reg)$PC2,pch=9,col=AncientAmurRiver_col,bg=AncientAmurRiver_col,cex=0.6)
# Ancient Nepal
reg="Nepal_Mebrak_2125BP.SG"
points(subset(frame,region==reg)$PC1,subset(frame,region==reg)$PC2,pch=1,col=AncientNepal_col,bg=AncientNepal_col,cex=0.6)
reg="Nepal_Samdzong_1500BP.SG"
points(subset(frame,region==reg)$PC1,subset(frame,region==reg)$PC2,pch=2,col=AncientNepal_col,bg=AncientNepal_col,cex=0.6)
reg="Nepal_Chokhopani_2700BP.SG"
points(subset(frame,region==reg)$PC1,subset(frame,region==reg)$PC2,pch=3,col=AncientNepal_col,bg=AncientNepal_col,cex=0.6)
# Ancient Southern Asia
reg="Qihe"
points(subset(frame,region==reg)$PC1,subset(frame,region==reg)$PC2,pch=1,col=AncientSouthernAsia_col,bg=AncientSouthernAsia_col,cex=0.6)
reg="Longlin"
points(subset(frame,region==reg)$PC1,subset(frame,region==reg)$PC2,pch=2,col=AncientSouthernAsia_col,bg=AncientSouthernAsia_col,cex=0.6)
reg="Tanshishan"
points(subset(frame,region==reg)$PC1,subset(frame,region==reg)$PC2,pch=3,col=AncientSouthernAsia_col,bg=AncientSouthernAsia_col,cex=0.6)
reg="Xitoucun"
points(subset(frame,region==reg)$PC1,subset(frame,region==reg)$PC2,pch=4,col=AncientSouthernAsia_col,bg=AncientSouthernAsia_col,cex=0.6)
reg="Suogang"
points(subset(frame,region==reg)$PC1,subset(frame,region==reg)$PC2,pch=5,col=AncientSouthernAsia_col,bg=AncientSouthernAsia_col,cex=0.6)
reg="Chuanyun"
points(subset(frame,region==reg)$PC1,subset(frame,region==reg)$PC2,pch=6,col=AncientSouthernAsia_col,bg=AncientSouthernAsia_col,cex=0.6)
reg="Liangdao1"
points(subset(frame,region==reg)$PC1,subset(frame,region==reg)$PC2,pch=7,col=AncientSouthernAsia_col,bg=AncientSouthernAsia_col,cex=0.6)
reg="Liangdao2"
points(subset(frame,region==reg)$PC1,subset(frame,region==reg)$PC2,pch=8,col=AncientSouthernAsia_col,bg=AncientSouthernAsia_col,cex=0.6)
reg="Taiwan_Hanben"
points(subset(frame,region==reg)$PC1,subset(frame,region==reg)$PC2,pch=9,col=AncientSouthernAsia_col,bg=AncientSouthernAsia_col,cex=0.6)
reg="Taiwan_Gongguan"
points(subset(frame,region==reg)$PC1,subset(frame,region==reg)$PC2,pch=10,col=AncientSouthernAsia_col,bg=AncientSouthernAsia_col,cex=0.6)
# Ancient Mongolia
reg="Mongolia_N_North"
points(subset(frame,region==reg)$PC1,subset(frame,region==reg)$PC2,pch=1,col=AncientMongolia_col,bg=AncientMongolia_col,cex=0.6)
reg="Mongolia_N_East"
points(subset(frame,region==reg)$PC1,subset(frame,region==reg)$PC2,pch=2,col=AncientMongolia_col,bg=AncientMongolia_col,cex=0.6)
reg="Mongolia_XiongNu.SG"
points(subset(frame,region==reg)$PC1,subset(frame,region==reg)$PC2,pch=3,col=AncientMongolia_col,bg=AncientMongolia_col,cex=0.6)
reg="Mongolia_Medieval"
points(subset(frame,region==reg)$PC1,subset(frame,region==reg)$PC2,pch=4,col=AncientMongolia_col,bg=AncientMongolia_col,cex=0.6)
reg="Mongolia_Mongol"
points(subset(frame,region==reg)$PC1,subset(frame,region==reg)$PC2,pch=5,col=AncientMongolia_col,bg=AncientMongolia_col,cex=0.6)
reg="Chandman_IA"
points(subset(frame,region==reg)$PC1,subset(frame,region==reg)$PC2,pch=6,col=AncientMongolia_col,bg=AncientMongolia_col,cex=0.6)
reg="earlyMed_Turk"
points(subset(frame,region==reg)$PC1,subset(frame,region==reg)$PC2,pch=7,col=AncientMongolia_col,bg=AncientMongolia_col,cex=0.6)
reg="earlyMed_Uigur"
points(subset(frame,region==reg)$PC1,subset(frame,region==reg)$PC2,pch=8,col=AncientMongolia_col,bg=AncientMongolia_col,cex=0.6)
reg="lateMed_Khitan"
points(subset(frame,region==reg)$PC1,subset(frame,region==reg)$PC2,pch=9,col=AncientMongolia_col,bg=AncientMongolia_col,cex=0.6)
reg="lateXiongnu"
points(subset(frame,region==reg)$PC1,subset(frame,region==reg)$PC2,pch=10,col=AncientMongolia_col,bg=AncientMongolia_col,cex=0.6)
reg="lateXiongnu_han"
points(subset(frame,region==reg)$PC1,subset(frame,region==reg)$PC2,pch=11,col=AncientMongolia_col,bg=AncientMongolia_col,cex=0.6)
reg="Rouran"
points(subset(frame,region==reg)$PC1,subset(frame,region==reg)$PC2,pch=12,col=AncientMongolia_col,bg=AncientMongolia_col,cex=0.6)
# Ancient Central Asian
reg="Tarim_EMBA1"
points(subset(frame,region==reg)$PC1,subset(frame,region==reg)$PC2,pch=1,col=AncientCentralAsian_col,bg=AncientCentralAsian_col,cex=0.6)
reg="Tarim_EMBA2"
points(subset(frame,region==reg)$PC1,subset(frame,region==reg)$PC2,pch=2,col=AncientCentralAsian_col,bg=AncientCentralAsian_col,cex=0.6)
reg="Dzungaria_EBA1"
points(subset(frame,region==reg)$PC1,subset(frame,region==reg)$PC2,pch=3,col=AncientCentralAsian_col,bg=AncientCentralAsian_col,cex=0.6)
reg="Dzungaria_EBA2"
points(subset(frame,region==reg)$PC1,subset(frame,region==reg)$PC2,pch=4,col=AncientCentralAsian_col,bg=AncientCentralAsian_col,cex=0.6)
reg="Kazakhstan_His.SG"
points(subset(frame,region==reg)$PC1,subset(frame,region==reg)$PC2,pch=5,col=AncientCentralAsian_col,bg=AncientCentralAsian_col,cex=0.6)
reg="Kazakhstan_Kangju.SG"
points(subset(frame,region==reg)$PC1,subset(frame,region==reg)$PC2,pch=6,col=AncientCentralAsian_col,bg=AncientCentralAsian_col,cex=0.6)
reg="Kazakhstan_Karakhanid.SG"
points(subset(frame,region==reg)$PC1,subset(frame,region==reg)$PC2,pch=7,col=AncientCentralAsian_col,bg=AncientCentralAsian_col,cex=0.6)
reg="Kazakhstan_Karluk.SG"
points(subset(frame,region==reg)$PC1,subset(frame,region==reg)$PC2,pch=8,col=AncientCentralAsian_col,bg=AncientCentralAsian_col,cex=0.6)
reg="Kazakhstan_Kimak.SG"
points(subset(frame,region==reg)$PC1,subset(frame,region==reg)$PC2,pch=9,col=AncientCentralAsian_col,bg=AncientCentralAsian_col,cex=0.6)
reg="Kazakhstan_Nomad_IA.SG"
points(subset(frame,region==reg)$PC1,subset(frame,region==reg)$PC2,pch=10,col=AncientCentralAsian_col,bg=AncientCentralAsian_col,cex=0.6)
reg="Kyrgyzstan_Medieval_Nomad.SG"
points(subset(frame,region==reg)$PC1,subset(frame,region==reg)$PC2,pch=11,col=AncientCentralAsian_col,bg=AncientCentralAsian_col,cex=0.6)
reg="Kazakhstan_TianShanSaka.SG"
points(subset(frame,region==reg)$PC1,subset(frame,region==reg)$PC2,pch=12,col=AncientCentralAsian_col,bg=AncientCentralAsian_col,cex=0.6)
reg="Kazakhstan_Wusun.SG"
points(subset(frame,region==reg)$PC1,subset(frame,region==reg)$PC2,pch=13,col=AncientCentralAsian_col,bg=AncientCentralAsian_col,cex=0.6)
reg="Kyrgyzstan_TianShanHun.SG"
points(subset(frame,region==reg)$PC1,subset(frame,region==reg)$PC2,pch=14,col=AncientCentralAsian_col,bg=AncientCentralAsian_col,cex=0.6)
# Ancient Russia
reg="DevilsCave_N.SG"
points(subset(frame,region==reg)$PC1,subset(frame,region==reg)$PC2,pch=1,col=AncientRussia_col,bg=AncientRussia_col,cex=0.6)
reg="Boisman_MN"
points(subset(frame,region==reg)$PC1,subset(frame,region==reg)$PC2,pch=2,col=AncientRussia_col,bg=AncientRussia_col,cex=0.6)
reg="Yankovsky_IA"
points(subset(frame,region==reg)$PC1,subset(frame,region==reg)$PC2,pch=3,col=AncientRussia_col,bg=AncientRussia_col,cex=0.6)
reg="Ekven_IA.SG"
points(subset(frame,region==reg)$PC1,subset(frame,region==reg)$PC2,pch=4,col=AncientRussia_col,bg=AncientRussia_col,cex=0.6)
reg="Russia_Heshui_Mohe_Early_Medieval"
points(subset(frame,region==reg)$PC1,subset(frame,region==reg)$PC2,pch=5,col=AncientRussia_col,bg=AncientRussia_col,cex=0.6)
reg="Russia_Alan.SG"
points(subset(frame,region==reg)$PC1,subset(frame,region==reg)$PC2,pch=6,col=AncientRussia_col,bg=AncientRussia_col,cex=0.6)
reg="Russia_Tagar.SG"
points(subset(frame,region==reg)$PC1,subset(frame,region==reg)$PC2,pch=7,col=AncientRussia_col,bg=AncientRussia_col,cex=0.6)
reg="Russia_Afanasievo"
points(subset(frame,region==reg)$PC1,subset(frame,region==reg)$PC2,pch=8,col=AncientRussia_col,bg=AncientRussia_col,cex=0.6)
reg="Russia_Kurma_EBA.SG"
points(subset(frame,region==reg)$PC1,subset(frame,region==reg)$PC2,pch=9,col=AncientRussia_col,bg=AncientRussia_col,cex=0.6)
reg="Russia_UstIda_EBA.SG"
points(subset(frame,region==reg)$PC1,subset(frame,region==reg)$PC2,pch=10,col=AncientRussia_col,bg=AncientRussia_col,cex=0.6)
reg="Russia_Andronovo.SG"
points(subset(frame,region==reg)$PC1,subset(frame,region==reg)$PC2,pch=11,col=AncientRussia_col,bg=AncientRussia_col,cex=0.6)
reg="Russia_Sarmatian.SG"
points(subset(frame,region==reg)$PC1,subset(frame,region==reg)$PC2,pch=12,col=AncientRussia_col,bg=AncientRussia_col,cex=0.6)
reg="Russia_North_Caucasus"
points(subset(frame,region==reg)$PC1,subset(frame,region==reg)$PC2,pch=13,col=AncientRussia_col,bg=AncientRussia_col,cex=0.6)
reg="Russia_Sintashta_MLBA.SG"
points(subset(frame,region==reg)$PC1,subset(frame,region==reg)$PC2,pch=14,col=AncientRussia_col,bg=AncientRussia_col,cex=0.6)
# Xianbei_related
reg="AR_Xianbei_IA"
points(subset(frame,region==reg)$PC1,subset(frame,region==reg)$PC2,pch=21,col=target_col,bg=target_bg,cex=0.6,lwd=1.2)
reg="Mongolia_IA_Xianbei"
points(subset(frame,region==reg)$PC1,subset(frame,region==reg)$PC2,pch=22,col=target_col,bg=target_bg,cex=0.6,lwd=1.2)
reg="Mongolia_Xianbei_ZHS5"
points(subset(frame,region==reg)$PC1,subset(frame,region==reg)$PC2,pch=23,col=target_col,bg=target_bg,cex=0.6,lwd=1.2)
reg="Tuoba_Xianbei_QL11"
points(subset(frame,region==reg)$PC1,subset(frame,region==reg)$PC2,pch=24,col=target_col,bg=target_bg,cex=0.6,lwd=1.2)
reg="Xianbei_Wudi"
points(subset(frame,region==reg)$PC1,subset(frame,region==reg)$PC2,pch=25,col=target_col,bg=target_bg,cex=0.6,lwd=1.2)
dev.off()

# LEGEND
pdf("legend.pdf")
par(mar=c(5,5,5,5))
plot.new()
pops=c("Han","Han_Fujian","Han_Guangdong","Han_Henan","Han_Hubei","Han_Jiangsu","Han_Shandong","Han_Shanghai","Han_Shanxi","Han_Sichuan","Han_Zhejiang","Han_Chongqing","Han_NChina","Han_HGDP","Austronesian","Ami","Malay","Atayal","Tagalog","Hmong-Mien","She","Dao","Miao","Gelao","Hmong","Japanese-Korean","Korean","Japanese","Mongolian","Tu","Daur","Yugur","Bonan","Buryat","Mongol","Mongola","Dongxiang","Tai-Kadai","Dai","Zhuang","Li","Dong_Hunan","Thai","Tay","BoY","CoLao","Nung","Tibetan-Burman","Yi","Naxi","Tujia","China_Lahu","Tibetan_Chamdo","Tibetan_Lhasa","Tibetan_Yunnan","Tibetan_Yajiang","Tibetan_Xinlong","Tungusic","Xibo","Hezhen","Oroqen","Ulchi","Evenk_FarEast","Ancient Yellow River","Yumin","Bianbian","Boshan","Xiaogao","Xiaojingshan","Miaozigou_MN","YR_MN","YR_LN","YR_LBIA","Shimao_LN","Upper_YR_LN","Upper_YR_IA","Ancient Amur River","AR19K","AR14K","ARpost9K","AR_EN","AR_IA","HMMH_MN","WLR_MN","WLR_LN","WLR_BA","Ancient Nepal","Nepal_Mebrak_2125BP.SG","Nepal_Samdzong_1500BP.SG","Nepal_Chokhopani_2700BP.SG","Ancient Southern Asia","Qihe","Longlin","Tanshishan","Xitoucun","Suogang","Chuanyun","Liangdao1","Liangdao2","Taiwan_Hanben","Taiwan_Gongguan","Ancient Mongolia","Mongolia_N_North","Mongolia_N_East","Mongolia_XiongNu.SG","Mongolia_Medieval","Mongolia_Mongol","Chandman_IA","earlyMed_Turk","earlyMed_Uigur","lateMed_Khitan","lateXiongnu","lateXiongnu_han","Rouran","Ancient Central Asian","Tarim_EMBA1","Tarim_EMBA2","Dzungaria_EBA1","Dzungaria_EBA2","Kazakhstan_His.SG","Kazakhstan_Kangju.SG","Kazakhstan_Karakhanid.SG","Kazakhstan_Karluk.SG","Kazakhstan_Kimak.SG","Kazakhstan_Nomad_IA.SG","Kyrgyzstan_Medieval_Nomad.SG","Kazakhstan_TianShanSaka.SG","Kazakhstan_Wusun.SG","Kyrgyzstan_TianShanHun.SG","Ancient Russia","DevilsCave_N.SG","Boisman_MN","Yankovsky_IA","Ekven_IA.SG","Russia_Heshui_Mohe_Early_Medieval","Russia_Alan.SG","Russia_Tagar.SG","Russia_Afanasievo","Russia_Kurma_EBA.SG","Russia_UstIda_EBA.SG","Russia_Andronovo.SG","Russia_Sarmatian.SG","Russia_North_Caucasus","Russia_Sintashta_MLBA.SG","Xianbei_related","AR_Xianbei_IA","Mongolia_IA_Xianbei","Mongolia_Xianbei_ZHS5","Tuoba_Xianbei_QL11","Xianbei_Wudi")
cols=c(NA,rep(Han_col, 13),NA,rep(Austronesian_col, 4),NA,rep(HmongMien_col, 5),NA,rep(JapaneseKorean_col, 2),NA,rep(Mongolian_col, 8),NA,rep(TaiKadai_col, 9),NA,rep(TibetanBurman_col, 9),NA,rep(Tungusic_col, 5),NA,rep(AncientYellowRiver_col, 12),NA,rep(AncientAmurRiver_col, 9),NA,rep(AncientNepal_col, 3),NA,rep(AncientSouthernAsia_col, 10),NA,rep(AncientMongolia_col, 12),NA,rep(AncientCentralAsian_col, 14),NA,rep(AncientRussia_col, 14),NA,rep(target_col, 5))
bgs=c(NA,rep(Han_col, 13),NA,rep(Austronesian_col, 4),NA,rep(HmongMien_col, 5),NA,rep(JapaneseKorean_col, 2),NA,rep(Mongolian_col, 8),NA,rep(TaiKadai_col, 9),NA,rep(TibetanBurman_col, 9),NA,rep(Tungusic_col, 5),NA,rep(AncientYellowRiver_col, 12),NA,rep(AncientAmurRiver_col, 9),NA,rep(AncientNepal_col, 3),NA,rep(AncientSouthernAsia_col, 10),NA,rep(AncientMongolia_col, 12),NA,rep(AncientCentralAsian_col, 14),NA,rep(AncientRussia_col, 14),NA,rep(target_bg, 5))
symb=c(NA,1,2,3,4,5,6,7,8,9,10,11,12,13,NA,1,2,3,4,NA,1,2,3,4,5,NA,1,2,NA,1,2,3,4,5,6,7,8,NA,1,2,3,4,5,6,7,8,9,NA,1,2,3,4,5,6,7,8,9,NA,1,2,3,4,5,NA,1,2,3,4,5,6,7,8,9,10,11,12,NA,1,2,3,4,5,6,7,8,9,NA,1,2,3,NA,1,2,3,4,5,6,7,8,9,10,NA,1,2,3,4,5,6,7,8,9,10,11,12,NA,1,2,3,4,5,6,7,8,9,10,11,12,13,14,NA,1,2,3,4,5,6,7,8,9,10,11,12,13,14,NA,21,22,23,24,25)
fonts=c(2,rep(1, 13),2,rep(1, 4),2,rep(1, 5),2,rep(1, 2),2,rep(1, 8),2,rep(1, 9),2,rep(1, 9),2,rep(1, 5),2,rep(1, 12),2,rep(1, 9),2,rep(1, 3),2,rep(1, 10),2,rep(1, 12),2,rep(1, 14),2,rep(1, 14),2,rep(1, 5))
legend("top",pops,pch=symb,pt.bg=bgs,col=cols,ncol=3,cex=0.4,pt.cex=0.4,bty="o",text.font=fonts,xpd=TRUE)
dev.off()
